# Travis-CI Build for BooJs
# see travis-ci.org for details

language: objective-c

env:
  global:
    - EnableNuGetPackageRestore=true
    - PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig/
  matrix:
    - MONO_VER="4.2.2"

install:
  # Obtain mono from a fast mirror (over 150Mb download), travis-ci seems to be hosted in NY
  # - wget "http://switch.dl.sourceforge.net/project/mono.mirror/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
  # - wget "http://softlayer-ams.dl.sourceforge.net/project/mono.mirror/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
  # - wget "http://hivelocity.dl.sourceforge.net/project/mono.mirror/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
  # Personal mirror (PLEASE DO NOT USE IT!)
  #- wget "http://s3.amazonaws.com/travis-mirror/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
  # Official download
  - wget "http://download.mono-project.com/archive/${MONO_VER}/macos-10-x86/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
  # Install mono
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg" -target /

before_script:
 # Build BooJs...
 - make rebuild

script:
 # Run Tests
 - make ci-tests

# Notify development list when needed
notifications:
 recipients:
   - drslump@pollinimini.net
 email:
   on_success: change
   on_failure: always
