# Travis-CI Build for BooJs
# see travis-ci.org for details

language: csharp
mono:
  - 3.12.1

install:
  - echo "nothing to install"

before_script:
 # Build BooJs...
 - make rebuild

script:
 # Run Tests
 - make ci-tests

# Notify development list when needed
notifications:
 recipients:
   - drslump@pollinimini.net
 email:
   on_success: change
   on_failure: always
