# Travis-CI Build for BooJs
# see travis-ci.org for details

language: objective-c

env:
  global:
    - EnableNuGetPackageRestore=true
    - PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig/
  matrix:
    - MONO_VER="3.2.3"

install:
  # Obtain mono from a fast mirror (over 150Mb download), travis-ci seems to be hosted in NY
  # - wget "http://switch.dl.sourceforge.net/project/mono.mirror/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
  # - wget "http://softlayer-ams.dl.sourceforge.net/project/mono.mirror/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
  # - wget "http://hivelocity.dl.sourceforge.net/project/mono.mirror/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
  # Personal mirror (PLEASE DO NOT USE IT!)
  - wget "http://s3.amazonaws.com/travis-mirror/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
  # Install mono
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg" -target /

before_script:
 # Build BooJs...
 - xbuild src/boojs.sln

script:
 # Run Tests
 - echo "Running tests..."
 - >
    mono --runtime=v4.0 --gc=boehm 
    lib/nunit/nunit-console.exe -nologo -nodots -domain=none -timeout=10000 -framework=4.0 -output=stdout.txt 
    -run="
     BooJs.Tests.BoojsFixtures,
     BooJs.Tests.ClassesFixtures,
     BooJs.Tests.DevelFixtures,
     BooJs.Tests.DucktypingFixtures,
     BooJs.Tests.PrimitivesFixtures,
     BooJs.Tests.SaveFileTest,
     BooJs.Tests.StatementsFixtures,
     BooJs.Tests.StdlibFixtures,
     BooJs.Tests.SourceMapTest
    "
    src/BooJs.Tests/bin/Debug/BooJs.Tests.dll

# Notify development list when needed
notifications:
 recipients:
   - drslump@pollinimini.net
 email:
   on_success: change
   on_failure: always
